# File: config/config.yaml
# Main configuration for the BreatheEasy project

# File and Directory Paths (relative to project root)
paths:
  data_file: data/Post-Processing/CSV_Files/Master_AQI_Dataset.csv
  models_dir: models/

# API Configuration
apis:
  aqicn:
    base_url: "https://api.waqi.info/feed"
  weatherapi:
    base_url: "http://api.weatherapi.com/v1/current.json"
  # Add other API configs here if needed

# Modeling Configuration
modeling:
  target_cities: # Cities to train models for and likely support in UI
    - Delhi
    - Mumbai
    - Bangalore
    - Chennai
    - Hyderabad
  prophet_model_version: "v2" # Version suffix for model filenames
  forecast_days: 5 # Default number of days to forecast ahead

# Logging Configuration (Example - can be refined later)
logging:
  level: INFO # Overall level for handlers (DEBUG, INFO, WARNING, ERROR)
  format: '%(asctime)s - [%(levelname)s] - %(name)s - %(filename)s:%(lineno)d - %(message)s' # Added logger name '%(name)s'
  log_to_file: true # Set to true to enable file logging
  log_filename: app.log # Name of the log file (will appear in project root)
  log_file_level: DEBUG # Log DEBUG and above to file, INFO and above to console (example)
  log_console_level: INFO # Log INFO and above to console
