#
# Main configuration for the BreatheEasy project.
#

# --- File and Directory Paths ---
# Relative to the project root directory.
paths:
  data_file: data/Post-Processing/CSV_Files/Master_AQI_Dataset.csv
  models_dir: models/

# --- API Configuration ---
apis:
  aqicn:
    base_url: "https://api.waqi.info/feed"
  weatherapi:
    base_url: "http://api.weatherapi.com/v1/current.json"
    forecast_url: "http://api.weatherapi.com/v1/forecast.json"

# --- Modeling Configuration ---
modeling:
  # List of cities for which models will be trained and predictions generated.
  target_cities:
    - Delhi
    - Mumbai
    - Bangalore
    - Chennai
    - Hyderabad

  # Version suffix for saving/loading Prophet models.
  # Change this to retrain models with new parameters.
  prophet_model_version: "v3_weather"

  # Number of days to forecast ahead.
  forecast_days: 3

  # Decay factor for applying historical residuals to the forecast.
  # A value of 0.85 means the residual's effect decreases by 15% each day.
  residual_decay_factor: 0.85

  # Weather features from the dataset to be used as regressors in the Prophet model.
  # Ensure these column names exist in the historical data and can be fetched
  # for future dates from the weather forecast API.
  weather_regressors:
    - temperature_2m
    - relative_humidity_2m
    - wind_speed_10m
    # - rain
    # - pressure_msl
    # - cloud_cover
    # - wind_gusts_10m
    # Note: Avoid using highly correlated features like apparent_temperature or dew_point_2m
    # if temperature_2m and relative_humidity_2m are already included.

# --- API Retry and Timeout Settings ---
api_timeout_seconds: 15
api_retries:
  default: 2
  weather_api_current: 2
  weather_api_forecast: 3
api_retry_delay_seconds:
  default: 1
  weather_api_current: 1
  weather_api_forecast: 2


# --- Logging Configuration ---
logging:
  # Overall level for handlers. Can be DEBUG, INFO, WARNING, ERROR, CRITICAL.
  level: INFO
  # Format for log messages. See Python's logging documentation for options.
  format: '%(asctime)s - [%(levelname)s] - %(name)s - %(filename)s:%(lineno)d - %(message)s'
  # Set to true to enable logging to a rotating file.
  log_to_file: true
  log_filename: app.log
  # Specific log levels for console and file handlers.
  log_file_level: DEBUG
  log_console_level: INFO